# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VLrPXeRJN2Y8uJRjnIVbVzzgzOCGyPWs
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
!pip install streamlit
from pathlib import Path

import streamlit as st

sns.set(style='dark')

st.subheader("data")

def workingday_df(df):
  workingday_bike = df.groupby(by="workingday").instant.nunique().reset_index()
  workingday_bike.rename(columns={"instant": "sum"}, inplace=True)
  workingday_bike

  return workingday_bike

def seasonday_df(df):
  seasonday_bike = df.groupby(by="season").instant.nunique().reset_index()
  seasonday_bike.rename(columns={"instant": "sum"}, inplace=True)
  seasonday_bike

  return seasonday_bike

def sidebar(df):
    df["dteday"] = pd.to_datetime(df["dteday"])
    min_date = df["dteday"].min()
    max_date = df["dteday"].max()
    with st.sidebar:

        st.image("https://www.brandcrowd.com/blog/wp-content/uploads/2019/06/bike-share.png")

        def on_change():
            st.session_state.date = date

        date = st.date_input(
            label="Rentang Waktu",
            min_value=min_date,
            max_value=max_date,
            value=[min_date, max_date],
            on_change=on_change
        )

    return date

day_df = pd.read_csv("https://raw.githubusercontent.com/cabbbbsss/my_portofolio/main/Bike-Sharing/dashboard.csv")

date = sidebar(day_df)
if len(date) == 2:
    main_df = day_df[(day_df["dteday"] >= str(date[0])) & (day_df["dteday"] <= str(date[1]))]
else:
    main_df = day_df[
        (day_df["dteday"] >= str(st.session_state.date[0])) & (day_df["dteday"] <= str(st.session_state.date[1]))]

working_day_df = workingday_df(main_df)
season_day_df = seasonday_df(main_df)

st.header("Bike Sharing Dashboard :bike:")
st.subheader("Working Day")
fig, ax = plt.subplots(figsize=(20, 10))
sns.barplot(
    y="sum",
    x="workingday",
    data=working_day_df.sort_values(by="workingday", ascending=False),
    ax=ax
)

ax.set_title("Bagaimana pengaruh hari kerja dan liburan terhadap pengguna Bike Sharing?", loc="center", fontsize=18)
ax.set_ylabel("Jumlah Pengguna")
ax.set_xlabel(None)
ax.tick_params(axis="x", labelsize=20)
ax.tick_params(axis="y", labelsize=15)
st.pyplot(fig)

st.header("Bike Sharing Dashboard :bike:")
st.subheader("Season")
fig, ax = plt.subplots(figsize=(20, 10))
sns.barplot(
    y="sum",
    x="season",
    data=season_day_df.sort_values(by="season", ascending=False),
    ax=ax
)

ax.set_title("Bagaimana pengaruh setiap musim terhadap pengguna Bike Sharing?", loc="center", fontsize=18)
ax.set_ylabel("Jumlah Pengguna")
ax.set_xlabel(None)
ax.tick_params(axis="x", labelsize=20)
ax.tick_params(axis="y", labelsize=15)
st.pyplot(fig)

st.caption('Copyright (c) Sabrina Salsabila Saleh')